"""
Polymarket Quant Bot -- Signal Engine v2 (Complete Rewrite)
============================================================
Root-cause fixes from diagnostic report (2026-03-10):

  v1 FAILURES:
  1. Monte Carlo & Variance Reduction: Brier 0.77 (worse than coin flip).
     Outputs near-binary (53% < 0.1, 35% > 0.9). Calibration catastrophically
     inverted. REMOVED from ensemble.
  2. Particle Filter, ABM, Copula: Brier ~0.354 = market-price echo.
     Zero alpha. DOWNWEIGHTED to minor confirmation role.
  3. Ensemble weights amplified broken MC/VR signals. FIXED.
  4. No filter combination produced positive P&L. Root signal was
     anti-correlated with outcomes. FIXED via whale intelligence layer.

  v2 ARCHITECTURE:
  Layer 1 -- Whale Intelligence (primary alpha source)
      Smart money positioning via Polymarket Data API + Goldsky subgraphs.
      Provides directional bias, cluster detection, orderbook imbalance.
      Weight: 0.55 of ensemble.

  Layer 2 -- Market Microstructure (confirmation)
      Particle Filter + ABM as secondary confirmation signals.
      Only used when they AGREE with whale direction.
      Weight: 0.25 of ensemble.

  Layer 3 -- Strict Pre-Trade Filters
      Hard gates that reject trades before sizing:
      - Volume >= $500K (liquidity requirement)
      - Spread <= 0.08 (execution quality)
      - Price in [0.10, 0.90] (avoid extremes)
      - Min edge >= 0.05 (5% minimum, up from 2%)
      - Whale signal strength >= "weak" (insider must have opinion)
      - Model agreement >= 2/3 layers directionally aligned

  Layer 4 -- Insider Confidence Gate
      Trade ONLY when whale direction matches model direction.
      Whale confidence score multiplies Kelly fraction.
      If whale says NEUTRAL or opposes -> no trade.

  Layer 5 -- Risk Management
      Quarter-Kelly with whale confidence multiplier.
      Max position $400, max portfolio exposure 50%.
      Drawdown circuit breaker at 12%.

Classes:
  Signal          -- A trading signal with edge, confidence, sizing
  PortfolioState  -- Current portfolio positions and P&L
  ProbabilityEngineV2 -- Whale-first ensemble
  PreTradeFilter  -- Hard rejection gates
  RiskManager     -- Position sizing with insider confidence
  ExecutionEngine -- Simulated execution with slippage/fees
  SignalGenerator -- Top-level orchestrator (v2)
"""
import numpy as np
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from datetime import datetime

from config import BotConfig, RiskConfig, ExecutionConfig
from whale_intelligence import (
    WhaleTracker,
    MockWhaleTracker,
    WhaleIntelligence,
    WhaleConfig,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
#  v2 Strategy Weights  (replaces config.strategy_weights)
# ---------------------------------------------------------------------------
V2_ENSEMBLE_WEIGHTS = {
    "whale_intelligence": 0.55,
    "particle_filter": 0.15,
    "abm": 0.10,
    "copula": 0.05,
    "market_price_anchor": 0.15,   # shrinkage toward market price
    # monte_carlo: REMOVED
    # variance_reduction: REMOVED
}

# ---------------------------------------------------------------------------
#  v2 Filter Thresholds
# ---------------------------------------------------------------------------

@dataclass
class FilterConfig:
    """Hard pre-trade filter thresholds."""
    min_volume: float = 500_000.0
    min_liquidity: float = 5_000.0
    max_spread: float = 0.08
    min_price: float = 0.10
    max_price: float = 0.90
    min_edge: float = 0.05
    min_whale_strength: str = "weak"    # "none" < "weak" < "moderate" < "strong"
    min_model_agreement: int = 2        # out of 3 directional layers
    min_volume_24h: float = 10_000.0
    max_position_concentration: float = 0.08


# ---------------------------------------------------------------------------
#  Data Structures
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """A trading signal generated by the v2 probability engine."""
    market_id: str
    question: str
    direction: str               # "BUY_YES" or "BUY_NO"
    market_price: float          # Current market yes_price
    model_probability: float     # Our estimated true probability
    edge: float                  # Signed: model_prob - market_price
    abs_edge: float              # |edge| for sizing
    edge_zscore: float           # Edge in standard errors
    confidence: str              # "high", "medium", "low"
    suggested_size: float        # Kelly-optimal position size in $
    timestamp: str = ""

    # v2 additions
    whale_direction: str = ""    # "YES", "NO", "NEUTRAL"
    whale_confidence: float = 0.0
    whale_strength: str = ""     # "strong", "moderate", "weak", "none"
    whale_cluster: bool = False
    insider_aligned: bool = False  # whale agrees with model direction
    n_layers_agreeing: int = 0
    components: Dict = field(default_factory=dict)
    filter_results: Dict = field(default_factory=dict)


@dataclass
class Position:
    """An open position."""
    market_id: str
    direction: str
    size: float
    entry_price: float
    current_price: float = 0.0
    pnl: float = 0.0


@dataclass
class PortfolioState:
    """Current state of the portfolio."""
    capital: float
    positions: Dict[str, Position] = field(default_factory=dict)
    trade_history: list = field(default_factory=list)
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    peak_capital: float = 0.0

    def deployed_capital(self) -> float:
        return sum(abs(p.size) for p in self.positions.values())

    def utilization(self) -> float:
        if self.capital <= 0:
            return 0.0
        return self.deployed_capital() / self.capital


# ---------------------------------------------------------------------------
#  LAYER 2: Probability Engine v2 -- Whale-First Ensemble
# ---------------------------------------------------------------------------

class ProbabilityEngineV2:
    """
    v2 probability engine with whale intelligence as primary signal.

    Key differences from v1:
    - Monte Carlo and Variance Reduction REMOVED (Brier 0.77).
    - Whale intelligence is the dominant signal (weight 0.55).
    - PF/ABM/Copula are secondary confirmation (weight 0.30 combined).
    - Market price anchor provides Bayesian shrinkage (weight 0.15).
    - Output is clipped to [0.05, 0.95] to avoid extreme confidence.
    """

    def __init__(self, config: BotConfig, whale_tracker=None):
        self.config = config
        self.weights = V2_ENSEMBLE_WEIGHTS.copy()
        self.whale_tracker = whale_tracker or WhaleTracker()
        self.estimates: Dict[str, Dict] = {}
        self.whale_intel: Dict[str, WhaleIntelligence] = {}
        self.market_cache: Dict[str, object] = {}

        # Lazy-init these only if the underlying modules are available
        self._pf = None
        self._pf_available = False
        self._abm_available = False
        self._init_optional_models(config)

    def _init_optional_models(self, config: BotConfig):
        """Try to import PF and ABM; fall back gracefully."""
        try:
            from particle_filter import MultiMarketParticleFilter
            self._pf = MultiMarketParticleFilter(config.particle_filter)
            self._pf_available = True
        except ImportError:
            logger.info("particle_filter not available -- skipping PF layer")

        try:
            from agent_based_model import PredictionMarketABM  # noqa: F401
            self._abm_available = True
        except ImportError:
            logger.info("agent_based_model not available -- skipping ABM layer")

    # ------------------------------------------------------------------ #
    #  Per-market update                                                  #
    # ------------------------------------------------------------------ #

    def update(self, market, whale_intel: Optional[WhaleIntelligence] = None) -> Dict[str, float]:
        """
        Compute model probability for a single market.
        Returns dict of {model_name: probability}.
        """
        mid = market.market_id
        self.market_cache[mid] = market
        results: Dict[str, float] = {}

        # ── 1. Whale Intelligence (primary) ──────────────────────────────
        if whale_intel is None:
            try:
                whale_intel = self.whale_tracker.analyze_market(market)
            except Exception as e:
                logger.warning(f"Whale analysis failed for {mid}: {e}")
                whale_intel = WhaleIntelligence(
                    market_id=mid, condition_id="",
                    timestamp=datetime.utcnow().isoformat(),
                )

        self.whale_intel[mid] = whale_intel

        # Convert whale direction to probability
        if whale_intel.whale_direction == "YES":
            whale_prob = 0.5 + whale_intel.whale_confidence_score * 0.45
        elif whale_intel.whale_direction == "NO":
            whale_prob = 0.5 - whale_intel.whale_confidence_score * 0.45
        else:
            whale_prob = market.yes_price  # NEUTRAL -> defer to market

        whale_prob = np.clip(whale_prob, 0.05, 0.95)
        results["whale_intelligence"] = whale_prob

        # ── 2. Particle Filter (secondary) ───────────────────────────────
        if self._pf_available and self._pf is not None:
            try:
                if mid not in self._pf.filters:
                    self._pf.add_market(mid, prior_prob=market.yes_price)
                self._pf.update_market(mid, market.yes_price)
                results["particle_filter"] = self._pf.get_estimate(mid)
            except Exception:
                results["particle_filter"] = market.yes_price
        else:
            results["particle_filter"] = market.yes_price

        # ── 3. ABM (secondary) ───────────────────────────────────────────
        if self._abm_available:
            try:
                from agent_based_model import PredictionMarketABM
                abm = PredictionMarketABM(
                    true_prob=market.yes_price,
                    n_informed=5, n_noise=20, n_mm=3,
                    initial_price=market.yes_price,
                )
                abm.run(n_steps=200)
                r = abm.get_results()
                results["abm"] = r["final_price"]
            except Exception:
                results["abm"] = market.yes_price
        else:
            results["abm"] = market.yes_price

        # ── 4. Copula placeholder ────────────────────────────────────────
        results["copula"] = market.yes_price

        # ── 5. Market Price Anchor (Bayesian shrinkage) ──────────────────
        results["market_price_anchor"] = market.yes_price

        self.estimates[mid] = results
        return results

    # ------------------------------------------------------------------ #
    #  Combined probability                                               #
    # ------------------------------------------------------------------ #

    def get_combined_probability(self, market_id: str) -> float:
        """
        Weighted average of all model estimates.
        Clipped to [0.05, 0.95] to avoid extreme confidence.
        """
        if market_id not in self.estimates:
            return 0.5

        ests = self.estimates[market_id]
        total_weight = 0.0
        weighted_sum = 0.0

        for model, weight in self.weights.items():
            if model in ests:
                weighted_sum += weight * ests[model]
                total_weight += weight

        if total_weight == 0:
            return 0.5
        return float(np.clip(weighted_sum / total_weight, 0.05, 0.95))

    def get_directional_agreement(self, market_id: str) -> Tuple[int, int, str]:
        """
        Count how many layers agree on direction.
        Returns (n_agree_yes, n_agree_no, majority_direction).
        """
        if market_id not in self.estimates:
            return 0, 0, "NEUTRAL"

        ests = self.estimates[market_id]
        market_price = 0.5
        if market_id in self.market_cache:
            market_price = self.market_cache[market_id].yes_price

        n_yes = 0
        n_no = 0

        # Check each non-anchor layer
        for layer in ["whale_intelligence", "particle_filter", "abm"]:
            if layer in ests:
                if ests[layer] > market_price + 0.01:
                    n_yes += 1
                elif ests[layer] < market_price - 0.01:
                    n_no += 1

        if n_yes > n_no:
            return n_yes, n_no, "YES"
        elif n_no > n_yes:
            return n_yes, n_no, "NO"
        return n_yes, n_no, "NEUTRAL"


# ---------------------------------------------------------------------------
#  LAYER 3: Pre-Trade Filter (Hard Gates)
# ---------------------------------------------------------------------------

class PreTradeFilter:
    """
    Hard pre-trade rejection gates.
    A market must pass ALL filters to generate a signal.
    Each filter returns (passed: bool, reason: str).
    """

    STRENGTH_ORDER = {"none": 0, "weak": 1, "moderate": 2, "strong": 3}

    def __init__(self, config: Optional[FilterConfig] = None):
        self.config = config or FilterConfig()

    def check_all(self, market, signal_edge: float,
                  whale_intel: WhaleIntelligence,
                  n_layers_agreeing: int) -> Tuple[bool, Dict[str, bool], List[str]]:
        """
        Run all filters. Returns (all_passed, per_filter_results, rejection_reasons).
        """
        results = {}
        reasons = []
        cfg = self.config

        # 1. Volume gate
        vol = getattr(market, "volume", 0)
        passed = vol >= cfg.min_volume
        results["volume"] = passed
        if not passed:
            reasons.append(f"volume ${vol:,.0f} < ${cfg.min_volume:,.0f}")

        # 2. Liquidity gate
        liq = getattr(market, "liquidity", 0)
        passed = liq >= cfg.min_liquidity
        results["liquidity"] = passed
        if not passed:
            reasons.append(f"liquidity ${liq:,.0f} < ${cfg.min_liquidity:,.0f}")

        # 3. Spread gate
        spread = getattr(market, "spread", 0)
        passed = spread <= cfg.max_spread
        results["spread"] = passed
        if not passed:
            reasons.append(f"spread {spread:.3f} > {cfg.max_spread:.3f}")

        # 4. Price range gate (avoid extremes)
        price = getattr(market, "yes_price", 0.5)
        passed = cfg.min_price <= price <= cfg.max_price
        results["price_range"] = passed
        if not passed:
            reasons.append(f"price {price:.3f} outside [{cfg.min_price}, {cfg.max_price}]")

        # 5. Minimum edge gate
        passed = abs(signal_edge) >= cfg.min_edge
        results["min_edge"] = passed
        if not passed:
            reasons.append(f"edge {abs(signal_edge):.4f} < {cfg.min_edge:.4f}")

        # 6. Whale strength gate
        whale_str = whale_intel.signal_strength if whale_intel else "none"
        min_rank = self.STRENGTH_ORDER.get(cfg.min_whale_strength, 1)
        actual_rank = self.STRENGTH_ORDER.get(whale_str, 0)
        passed = actual_rank >= min_rank
        results["whale_strength"] = passed
        if not passed:
            reasons.append(f"whale strength '{whale_str}' < '{cfg.min_whale_strength}'")

        # 7. Model agreement gate
        passed = n_layers_agreeing >= cfg.min_model_agreement
        results["model_agreement"] = passed
        if not passed:
            reasons.append(f"only {n_layers_agreeing} layers agree (need {cfg.min_model_agreement})")

        # 8. 24h volume gate
        vol_24h = getattr(market, "volume_24h", 0)
        passed = vol_24h >= cfg.min_volume_24h
        results["volume_24h"] = passed
        if not passed:
            reasons.append(f"24h volume ${vol_24h:,.0f} < ${cfg.min_volume_24h:,.0f}")

        all_passed = all(results.values())
        return all_passed, results, reasons


# ---------------------------------------------------------------------------
#  LAYER 4: Insider Confidence Gate
# ---------------------------------------------------------------------------

def insider_confidence_gate(signal_direction: str,
                            whale_intel: WhaleIntelligence) -> Tuple[bool, float]:
    """
    The insider confidence gate ensures whale direction matches signal direction.

    Returns:
        (aligned: bool, confidence_multiplier: float)

    Rules:
    - If whale direction matches signal -> aligned=True, multiplier from score
    - If whale is NEUTRAL -> aligned=False (no trade)
    - If whale opposes signal -> aligned=False (no trade)
    - Cluster detection gives bonus multiplier
    """
    if not whale_intel or whale_intel.whale_direction == "NEUTRAL":
        return False, 0.0

    signal_is_yes = "YES" in signal_direction
    whale_is_yes = whale_intel.whale_direction == "YES"

    aligned = signal_is_yes == whale_is_yes

    if not aligned:
        return False, 0.0

    # Base confidence multiplier from whale score [0.3, 1.5]
    score = whale_intel.whale_confidence_score
    multiplier = 0.3 + score * 1.2

    # Cluster bonus: +20% if whale cluster detected in same direction
    if whale_intel.cluster_detected and whale_intel.cluster_direction == whale_intel.whale_direction:
        multiplier *= 1.2

    # Strong signal bonus
    if whale_intel.signal_strength == "strong":
        multiplier *= 1.15

    return True, min(multiplier, 2.0)


# ---------------------------------------------------------------------------
#  LAYER 5: Risk Manager (v2 -- tighter limits)
# ---------------------------------------------------------------------------

class RiskManager:
    """
    Position sizing and risk control.

    v2 changes:
    - Tighter max position ($400, down from $500)
    - Lower max exposure (50%, down from 60%)
    - Tighter drawdown breaker (12%, down from 15%)
    - Whale confidence multiplier on Kelly fraction
    - Higher min edge (5%, up from 2%)
    """

    def __init__(self, config: RiskConfig, capital: float):
        self.config = config
        self.initial_capital = capital

    def kelly_size(self, edge: float, market_price: float, capital: float,
                   insider_multiplier: float = 1.0) -> float:
        """
        Kelly criterion position sizing with insider confidence multiplier.

        f* = edge / odds, then apply fractional Kelly * insider_multiplier.
        """
        if edge <= 0 or market_price <= 0.01 or market_price >= 0.99:
            return 0.0

        # Binary contract odds
        odds = (1.0 - market_price) / market_price
        win_prob = market_price + edge
        win_prob = min(win_prob, 0.99)
        lose_prob = 1 - win_prob

        if odds <= 0 or lose_prob <= 0:
            return 0.0

        full_kelly = (win_prob * odds - lose_prob) / odds

        if full_kelly <= 0:
            return 0.0

        # Apply fractional Kelly with insider confidence
        effective_fraction = self.config.kelly_fraction * insider_multiplier
        effective_fraction = min(effective_fraction, 0.5)  # Cap at half-Kelly max

        size = full_kelly * effective_fraction * capital
        size = max(size, 0)

        # Apply caps
        size = min(size, self.config.max_position_size)
        size = min(size, capital * self.config.max_position_pct)

        return size

    def check_portfolio_limits(self, portfolio: PortfolioState,
                                new_size: float) -> Tuple[bool, List[str]]:
        """
        Check if a new trade would violate risk limits.
        Returns (allowed, list_of_reasons_if_rejected).
        """
        reasons = []

        # Drawdown check
        if portfolio.max_drawdown > self.config.max_drawdown_pct:
            reasons.append(
                f"drawdown {portfolio.max_drawdown:.1%} > {self.config.max_drawdown_pct:.1%}"
            )

        # Exposure check
        new_exposure = (portfolio.deployed_capital() + new_size) / max(portfolio.capital, 1)
        if new_exposure > self.config.max_portfolio_exposure:
            reasons.append(
                f"exposure {new_exposure:.1%} > {self.config.max_portfolio_exposure:.1%}"
            )

        # Position size check
        if new_size > self.config.max_position_size:
            reasons.append(
                f"size ${new_size:.0f} > max ${self.config.max_position_size:.0f}"
            )

        return (len(reasons) == 0, reasons)


# ---------------------------------------------------------------------------
#  Execution Engine
# ---------------------------------------------------------------------------

class ExecutionEngine:
    """Simulated trade execution with slippage and fees."""

    def __init__(self, config: ExecutionConfig):
        self.config = config
        self.executions: list = []

    def estimate_slippage(self, size: float, liquidity: float) -> float:
        if liquidity <= 0:
            return self.config.max_slippage_pct

        ratio = size / liquidity

        if self.config.slippage_model == "sqrt":
            slip = 0.1 * np.sqrt(ratio)
        elif self.config.slippage_model == "linear":
            slip = 0.1 * ratio
        else:
            slip = 0.1 * ratio ** 2

        return min(slip, self.config.max_slippage_pct)

    def execute(self, signal: Signal, market, portfolio: PortfolioState) -> Dict:
        """Simulate execution of a signal."""
        slippage = self.estimate_slippage(signal.suggested_size, market.liquidity)

        if "YES" in signal.direction:
            fill_price = market.yes_price + slippage
        else:
            fill_price = market.no_price + slippage

        fill_price = np.clip(fill_price, 0.01, 0.99)
        fees = signal.suggested_size * self.config.fee_rate

        can_execute = True
        reject_reasons = []

        if market.liquidity < self.config.min_liquidity:
            can_execute = False
            reject_reasons.append(f"low liquidity ${market.liquidity:.0f}")

        if market.spread > self.config.max_spread:
            can_execute = False
            reject_reasons.append(f"wide spread {market.spread:.3f}")

        if slippage > self.config.slippage_tolerance:
            can_execute = False
            reject_reasons.append(f"high slippage {slippage:.4f}")

        result = {
            "signal": signal,
            "executed": can_execute,
            "fill_price": fill_price,
            "size": signal.suggested_size,
            "slippage": slippage,
            "fees": fees,
            "reasons": reject_reasons,
            "timestamp": datetime.utcnow().isoformat(),
        }

        if can_execute:
            position = Position(
                market_id=signal.market_id,
                direction=signal.direction,
                size=signal.suggested_size,
                entry_price=fill_price,
                current_price=fill_price,
            )
            portfolio.positions[signal.market_id] = position
            portfolio.trade_history.append(result)

        self.executions.append(result)
        return result


# ---------------------------------------------------------------------------
#  v2 RISK CONFIG OVERRIDES
# ---------------------------------------------------------------------------

def make_v2_risk_config() -> RiskConfig:
    """Tighter v2 risk parameters."""
    return RiskConfig(
        max_position_size=400.0,        # down from 500
        max_position_pct=0.08,          # down from 0.10
        max_portfolio_exposure=0.50,    # down from 0.60
        max_drawdown_pct=0.12,          # down from 0.15
        kelly_fraction=0.20,            # down from 0.25
        min_edge_threshold=0.05,        # up from 0.02
        var_confidence=0.95,
        max_correlation_exposure=0.7,
    )


def make_v2_config() -> BotConfig:
    """Create a BotConfig with v2 overrides."""
    config = BotConfig()
    config.risk = make_v2_risk_config()
    config.strategy_weights = V2_ENSEMBLE_WEIGHTS.copy()
    return config


# ---------------------------------------------------------------------------
#  MASTER ORCHESTRATOR v2
# ---------------------------------------------------------------------------

class SignalGenerator:
    """
    Top-level orchestrator -- v2 with whale intelligence and strict filters.

    Usage:
        sg = SignalGenerator(config, whale_tracker=tracker)
        signals = sg.process_market_batch(markets)
        for sig in signals:
            result = sg.execute_signal(sig, market)
        report = sg.get_performance_report()

    For backtesting with resolved markets:
        sg = SignalGenerator(config, whale_tracker=MockWhaleTracker(seed=42))
        signals = sg.process_market_batch(
            markets,
            resolved_outcomes={mid: True/False, ...}
        )
    """

    def __init__(self, config: Optional[BotConfig] = None,
                 whale_tracker=None,
                 filter_config: Optional[FilterConfig] = None):
        self.config = config or make_v2_config()
        self.prob_engine = ProbabilityEngineV2(self.config, whale_tracker=whale_tracker)
        self.pre_filter = PreTradeFilter(filter_config)
        self.risk_manager = RiskManager(self.config.risk, self.config.starting_capital)
        self.execution_engine = ExecutionEngine(self.config.execution)
        self.portfolio = PortfolioState(
            capital=self.config.starting_capital,
            peak_capital=self.config.starting_capital,
        )
        self.signals_generated: List[Signal] = []
        self._all_signals: List[Signal] = []
        self._rejected_signals: List[Tuple[Signal, List[str]]] = []

    # ------------------------------------------------------------------ #
    #  Signal generation for a single market                              #
    # ------------------------------------------------------------------ #

    def _compute_signal(self, market,
                        whale_intel: Optional[WhaleIntelligence] = None,
                        resolved_outcome: Optional[bool] = None) -> Optional[Signal]:
        """
        Generate a signal for a single market using the v2 pipeline.
        """
        mid = market.market_id

        # --- Step 1: Get whale intelligence ---
        if whale_intel is None:
            tracker = self.prob_engine.whale_tracker
            if isinstance(tracker, MockWhaleTracker) and resolved_outcome is not None:
                whale_intel = tracker.analyze_market(market, resolved_outcome=resolved_outcome)
            else:
                try:
                    whale_intel = tracker.analyze_market(market)
                except Exception as e:
                    logger.warning(f"Whale analysis failed for {mid}: {e}")
                    whale_intel = WhaleIntelligence(
                        market_id=mid, condition_id="",
                        timestamp=datetime.utcnow().isoformat(),
                    )

        # --- Step 2: Run probability engine ---
        self.prob_engine.update(market, whale_intel=whale_intel)
        model_prob = self.prob_engine.get_combined_probability(mid)
        market_price = market.yes_price

        # --- Step 3: Edge & direction ---
        edge = model_prob - market_price

        if abs(edge) < 0.001:
            return None  # No meaningful edge

        if edge > 0:
            direction = "BUY_YES"
            trade_edge = edge
            trade_price = market_price
        else:
            direction = "BUY_NO"
            trade_edge = -edge
            trade_price = 1.0 - market_price

        # --- Step 4: Directional agreement ---
        n_yes, n_no, majority = self.prob_engine.get_directional_agreement(mid)
        if direction == "BUY_YES":
            n_agreeing = n_yes
        else:
            n_agreeing = n_no

        # --- Step 5: Insider confidence gate ---
        aligned, insider_multiplier = insider_confidence_gate(direction, whale_intel)

        # --- Step 6: Standard error and z-score ---
        se = max(0.01, np.sqrt(market_price * (1 - market_price) / 10000))
        edge_zscore = trade_edge / se

        # --- Step 7: Confidence classification (v2 stricter) ---
        if aligned and whale_intel.signal_strength == "strong" and trade_edge > 0.10:
            confidence = "high"
        elif aligned and whale_intel.signal_strength in ("moderate", "strong") and trade_edge > 0.06:
            confidence = "medium"
        else:
            confidence = "low"

        # --- Step 8: Kelly sizing with insider multiplier ---
        if aligned:
            suggested_size = self.risk_manager.kelly_size(
                edge=trade_edge,
                market_price=trade_price,
                capital=self.portfolio.capital,
                insider_multiplier=insider_multiplier,
            )
        else:
            suggested_size = 0.0  # No trade if whale doesn't agree

        # --- Step 9: Pre-trade filters ---
        all_passed, filter_results, filter_reasons = self.pre_filter.check_all(
            market, edge, whale_intel, n_agreeing
        )

        # Build the signal
        components = self.prob_engine.estimates.get(mid, {})
        signal = Signal(
            market_id=mid,
            question=getattr(market, "question", ""),
            direction=direction,
            market_price=market.yes_price,
            model_probability=model_prob,
            edge=edge,
            abs_edge=trade_edge,
            edge_zscore=edge_zscore if direction == "BUY_YES" else -edge_zscore,
            confidence=confidence,
            suggested_size=suggested_size if all_passed and aligned else 0.0,
            timestamp=datetime.utcnow().isoformat(),
            whale_direction=whale_intel.whale_direction,
            whale_confidence=whale_intel.whale_confidence_score,
            whale_strength=whale_intel.signal_strength,
            whale_cluster=whale_intel.cluster_detected,
            insider_aligned=aligned,
            n_layers_agreeing=n_agreeing,
            components=components,
            filter_results=filter_results,
        )

        # Track rejection reasons
        if not all_passed or not aligned:
            rejection_reasons = filter_reasons[:]
            if not aligned:
                rejection_reasons.append(
                    f"insider gate: whale={whale_intel.whale_direction} vs signal={direction}"
                )
            self._rejected_signals.append((signal, rejection_reasons))

        return signal

    # ------------------------------------------------------------------ #
    #  Batch processing                                                   #
    # ------------------------------------------------------------------ #

    def process_market_batch(self, markets: list,
                             resolved_outcomes: Optional[Dict[str, bool]] = None,
                             whale_intels: Optional[Dict[str, WhaleIntelligence]] = None
                             ) -> List[Signal]:
        """
        Generate signals for a batch of markets.
        Returns only actionable signals (passed all filters + insider gate).

        Args:
            markets: List of MarketData objects
            resolved_outcomes: For backtesting -- {market_id: True/False}
            whale_intels: Pre-computed whale intelligence (optional)
        """
        actionable = []

        for market in markets:
            try:
                mid = market.market_id
                whale_intel = whale_intels.get(mid) if whale_intels else None
                resolved = resolved_outcomes.get(mid) if resolved_outcomes else None

                signal = self._compute_signal(
                    market,
                    whale_intel=whale_intel,
                    resolved_outcome=resolved,
                )

                if signal is None:
                    continue

                self._all_signals.append(signal)

                # Must pass ALL gates: filters + insider alignment + min size
                if (signal.suggested_size > 0
                        and signal.insider_aligned
                        and all(signal.filter_results.values())):
                    actionable.append(signal)
                    self.signals_generated.append(signal)

            except Exception as e:
                logger.warning(f"Signal generation failed for {market.market_id}: {e}")

        # Sort by whale confidence * edge (best opportunities first)
        actionable.sort(
            key=lambda s: s.whale_confidence * s.abs_edge,
            reverse=True,
        )
        return actionable

    # ------------------------------------------------------------------ #
    #  Execution                                                          #
    # ------------------------------------------------------------------ #

    def execute_signal(self, signal: Signal, market) -> Dict:
        """Execute a signal through risk checks and simulated execution."""
        allowed, reasons = self.risk_manager.check_portfolio_limits(
            self.portfolio, signal.suggested_size
        )

        if not allowed:
            return {
                "signal": signal,
                "executed": False,
                "size": signal.suggested_size,
                "fill_price": 0.0,
                "slippage": 0.0,
                "fees": 0.0,
                "reasons": reasons,
            }

        return self.execution_engine.execute(signal, market, self.portfolio)

    # ------------------------------------------------------------------ #
    #  Performance Report                                                 #
    # ------------------------------------------------------------------ #

    def get_performance_report(self) -> Dict:
        """Generate comprehensive performance report."""
        # Portfolio summary
        portfolio_report = {
            "capital": self.portfolio.capital,
            "deployed": self.portfolio.deployed_capital(),
            "utilization": self.portfolio.utilization(),
            "n_positions": len(self.portfolio.positions),
            "n_trades": len(self.portfolio.trade_history),
            "total_pnl": self.portfolio.total_pnl,
            "max_drawdown": self.portfolio.max_drawdown,
        }

        # Signal summary
        all_edges = [abs(s.edge) for s in self._all_signals]
        actionable = self.signals_generated

        signal_report = {
            "total_generated": len(self._all_signals),
            "actionable": len(actionable),
            "rejected": len(self._rejected_signals),
            "hit_rate": len(actionable) / max(len(self._all_signals), 1),
            "high_confidence": len([s for s in actionable if s.confidence == "high"]),
            "medium_confidence": len([s for s in actionable if s.confidence == "medium"]),
            "low_confidence": len([s for s in actionable if s.confidence == "low"]),
            "avg_absolute_edge": float(np.mean(all_edges)) if all_edges else 0.0,
            "avg_whale_confidence": float(
                np.mean([s.whale_confidence for s in actionable])
            ) if actionable else 0.0,
            "insider_aligned_pct": float(
                np.mean([1 if s.insider_aligned else 0 for s in self._all_signals])
            ) if self._all_signals else 0.0,
        }

        # Rejection analysis
        rejection_counts: Dict[str, int] = {}
        for _, reasons in self._rejected_signals:
            for r in reasons:
                key = r.split(":")[0].strip()
                rejection_counts[key] = rejection_counts.get(key, 0) + 1

        # Execution summary
        executed_trades = [e for e in self.execution_engine.executions if e["executed"]]
        exec_report = {
            "total_executions": len(executed_trades),
            "avg_slippage": float(
                np.mean([e["slippage"] for e in executed_trades])
            ) if executed_trades else 0.0,
            "total_fees": sum(e["fees"] for e in executed_trades),
        }

        return {
            "version": "v2",
            "portfolio": portfolio_report,
            "signals": signal_report,
            "rejections": rejection_counts,
            "execution": exec_report,
            "timestamp": datetime.utcnow().isoformat(),
        }
