"""
Polymarket Quant Bot — Signal Engine & Risk Manager (Article Part VIII Layers 2-4)
===================================================================================
The production stack that ties all quant modules together.

LAYER 2: PROBABILITY ENGINE
  Combines Monte Carlo, particle filter, variance reduction, and ABM estimates
  into a single "model probability" per contract.

LAYER 3: DEPENDENCY MODELING
  Uses copulas to model cross-market correlations.

LAYER 4: RISK MANAGEMENT
  Kelly criterion sizing, drawdown limits, exposure caps.

LAYER 5: MONITORING
  Brier scores, P&L attribution, signal tracking.

Classes:
  Signal          — A trading signal with edge, confidence, sizing
  PortfolioState  — Current portfolio positions and P&L
  ProbabilityEngine — Combines all models into one estimate
  RiskManager     — Position sizing and exposure control
  ExecutionEngine — Simulated execution with slippage/fees
  SignalGenerator — Top-level orchestrator
"""
import numpy as np
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from datetime import datetime

from config import BotConfig, RiskConfig, ExecutionConfig
from monte_carlo import simulate_binary_contract, brier_score
from particle_filter import MultiMarketParticleFilter
from variance_reduction import stacked_variance_reduction
from copula_engine import simulate_gaussian_copula
from agent_based_model import PredictionMarketABM

logger = logging.getLogger(__name__)


# --- Data Structures ---

@dataclass
class Signal:
    """A trading signal generated by the probability engine."""
    market_id: str
    question: str
    direction: str          # "BUY_YES", "BUY_NO", "SELL_YES", "SELL_NO"
    market_price: float     # Current market yes_price
    model_probability: float  # Our estimated true probability
    edge: float             # model_probability - market_price (signed)
    edge_zscore: float      # Edge in standard errors
    confidence: str         # "high", "medium", "low"
    suggested_size: float   # Kelly-optimal position size in $
    timestamp: str = ""
    components: Dict = field(default_factory=dict)


@dataclass
class Position:
    """An open position."""
    market_id: str
    direction: str
    size: float
    entry_price: float
    current_price: float = 0.0
    pnl: float = 0.0


@dataclass
class PortfolioState:
    """Current state of the portfolio."""
    capital: float
    positions: Dict[str, Position] = field(default_factory=dict)
    trade_history: list = field(default_factory=list)
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    peak_capital: float = 0.0

    def deployed_capital(self) -> float:
        return sum(abs(p.size) for p in self.positions.values())

    def utilization(self) -> float:
        if self.capital <= 0:
            return 0.0
        return self.deployed_capital() / self.capital


# --- LAYER 2: Probability Engine ---

class ProbabilityEngine:
    """
    Combines multiple model estimates into a single probability.

    Models:
    - Monte Carlo GBM (base)
    - Particle Filter (real-time update)
    - Variance Reduction (refined estimate)
    - ABM (microstructure view)

    Weights from config.strategy_weights.
    """

    def __init__(self, config: BotConfig):
        self.config = config
        self.weights = config.strategy_weights
        self.filters = MultiMarketParticleFilter(config.particle_filter)
        self.estimates: Dict[str, Dict] = {}  # market_id -> {model: prob}
        self.market_cache: Dict[str, object] = {}  # market_id -> MarketData

    def update(self, market) -> Dict[str, float]:
        """
        Compute model probability for a single market.
        Returns dict of {model_name: probability}.
        """
        mid = market.market_id
        self.market_cache[mid] = market

        results = {}

        # 1. Monte Carlo GBM estimate
        try:
            vol = max(abs(market.one_week_price_change) * 4, 0.3) if market.one_week_price_change != 0 else 0.5
            T = max(market.time_to_expiry_days / 365, 1/365)
            mc = simulate_binary_contract(
                S0=market.yes_price * 100,
                K=50.0,
                sigma=vol,
                T=T,
                N=self.config.monte_carlo.n_simulations // 10,  # lighter for speed
            )
            results["monte_carlo"] = mc["p_mc"]
        except Exception:
            results["monte_carlo"] = market.yes_price

        # 2. Particle Filter
        try:
            if mid not in self.filters.filters:
                self.filters.add_market(mid, prior_prob=market.yes_price)
            self.filters.update_market(mid, market.yes_price)
            results["particle_filter"] = self.filters.get_estimate(mid)
        except Exception:
            results["particle_filter"] = market.yes_price

        # 3. Variance Reduction estimate
        try:
            vol_vr = max(abs(market.one_week_price_change) * 4, 0.3) if market.one_week_price_change != 0 else 0.5
            T_vr = max(market.time_to_expiry_days / 365, 1/365)
            vr = stacked_variance_reduction(
                S0=market.yes_price * 100,
                K=50.0,
                sigma=vol_vr,
                T=T_vr,
                N_total=self.config.variance_reduction.n_simulations // 10,
            )
            results["variance_reduction"] = vr["p_stacked"]
        except Exception:
            results["variance_reduction"] = market.yes_price

        # 4. ABM estimate
        try:
            abm = PredictionMarketABM(
                true_prob=market.yes_price,
                n_informed=5,
                n_noise=20,
                n_mm=3,
                initial_price=market.yes_price,
            )
            abm.run(n_steps=200)  # Quick run
            r = abm.get_results()
            results["abm"] = r["final_price"]
        except Exception:
            results["abm"] = market.yes_price

        # 5. Copula contribution (default to market price)
        results["copula"] = market.yes_price  # Updated when cross-market analysis runs

        self.estimates[mid] = results
        return results

    def get_combined_probability(self, market_id: str) -> float:
        """
        Weighted average of all model estimates.
        """
        if market_id not in self.estimates:
            return 0.5

        ests = self.estimates[market_id]
        total_weight = 0.0
        weighted_sum = 0.0

        for model, weight in self.weights.items():
            if model in ests:
                weighted_sum += weight * ests[model]
                total_weight += weight

        if total_weight == 0:
            return 0.5
        return np.clip(weighted_sum / total_weight, 0.01, 0.99)


# --- LAYER 4: Risk Manager ---

class RiskManager:
    """
    Position sizing and risk control.

    Implements:
    - Kelly criterion (fractional)
    - Maximum position size
    - Portfolio exposure limits
    - Drawdown circuit breaker
    """

    def __init__(self, config: RiskConfig, capital: float):
        self.config = config
        self.initial_capital = capital

    def kelly_size(self, edge: float, market_price: float, capital: float) -> float:
        """
        Kelly criterion position sizing.
        f* = edge / odds, then apply fractional Kelly.
        """
        if edge <= 0 or market_price <= 0 or market_price >= 1:
            return 0.0

        # Binary contract odds
        if edge > 0:  # BUY_YES
            odds = (1.0 - market_price) / market_price
        else:  # BUY_NO
            odds = market_price / (1.0 - market_price)

        win_prob = market_price + abs(edge)
        lose_prob = 1 - win_prob

        if odds <= 0 or lose_prob <= 0:
            return 0.0

        full_kelly = (win_prob * odds - lose_prob) / odds
        fractional = full_kelly * self.config.kelly_fraction

        # Apply caps
        size = max(fractional * capital, 0)
        size = min(size, self.config.max_position_size)
        size = min(size, capital * self.config.max_position_pct)

        return size

    def check_portfolio_limits(self, portfolio: PortfolioState,
                                new_size: float) -> Tuple[bool, List[str]]:
        """
        Check if a new trade would violate risk limits.
        Returns (allowed, list_of_reasons_if_rejected).
        """
        reasons = []

        # Drawdown check
        if portfolio.max_drawdown > self.config.max_drawdown_pct:
            reasons.append(f"drawdown {portfolio.max_drawdown:.1%} > {self.config.max_drawdown_pct:.1%}")

        # Exposure check
        new_exposure = (portfolio.deployed_capital() + new_size) / max(portfolio.capital, 1)
        if new_exposure > self.config.max_portfolio_exposure:
            reasons.append(f"exposure {new_exposure:.1%} > {self.config.max_portfolio_exposure:.1%}")

        # Position size check
        if new_size > self.config.max_position_size:
            reasons.append(f"size ${new_size:.0f} > max ${self.config.max_position_size:.0f}")

        return (len(reasons) == 0, reasons)


# --- Execution Engine ---

class ExecutionEngine:
    """
    Simulated trade execution with slippage and fees.
    """

    def __init__(self, config: ExecutionConfig):
        self.config = config
        self.executions: list = []

    def estimate_slippage(self, size: float, liquidity: float) -> float:
        """
        Estimate slippage based on order size vs liquidity.
        Uses sqrt model by default (empirically most accurate).
        """
        if liquidity <= 0:
            return self.config.max_slippage_pct

        ratio = size / liquidity

        if self.config.slippage_model == "sqrt":
            slip = 0.1 * np.sqrt(ratio)
        elif self.config.slippage_model == "linear":
            slip = 0.1 * ratio
        else:  # quadratic
            slip = 0.1 * ratio ** 2

        return min(slip, self.config.max_slippage_pct)

    def execute(self, signal: Signal, market, portfolio: PortfolioState) -> Dict:
        """
        Simulate execution of a signal. Returns execution details.
        """
        slippage = self.estimate_slippage(signal.suggested_size, market.liquidity)

        # Adjust fill price for slippage
        if "YES" in signal.direction:
            fill_price = market.yes_price + slippage
        else:
            fill_price = market.no_price + slippage

        fill_price = np.clip(fill_price, 0.01, 0.99)

        # Fees
        fees = signal.suggested_size * self.config.fee_rate

        # Check liquidity
        can_execute = True
        reject_reasons = []

        if market.liquidity < self.config.min_liquidity:
            can_execute = False
            reject_reasons.append(f"low liquidity ${market.liquidity:.0f}")

        if market.spread > self.config.max_spread:
            can_execute = False
            reject_reasons.append(f"wide spread {market.spread:.3f}")

        if slippage > self.config.slippage_tolerance:
            can_execute = False
            reject_reasons.append(f"high slippage {slippage:.4f}")

        result = {
            "signal": signal,
            "executed": can_execute,
            "fill_price": fill_price,
            "size": signal.suggested_size,
            "slippage": slippage,
            "fees": fees,
            "reasons": reject_reasons,
            "timestamp": datetime.utcnow().isoformat(),
        }

        if can_execute:
            # Update portfolio
            position = Position(
                market_id=signal.market_id,
                direction=signal.direction,
                size=signal.suggested_size,
                entry_price=fill_price,
                current_price=fill_price,
            )
            portfolio.positions[signal.market_id] = position
            portfolio.trade_history.append(result)

        self.executions.append(result)
        return result


# --- MASTER ORCHESTRATOR ---

class SignalGenerator:
    """
    Top-level orchestrator that combines all layers.

    Usage:
        sg = SignalGenerator(config)
        for market in markets:
            sg.prob_engine.update(market)
        signals = sg.process_market_batch(markets)
        for sig in signals:
            result = sg.execute_signal(sig, market)
        report = sg.get_performance_report()
    """

    def __init__(self, config: BotConfig):
        self.config = config
        self.prob_engine = ProbabilityEngine(config)
        self.risk_manager = RiskManager(config.risk, config.starting_capital)
        self.execution_engine = ExecutionEngine(config.execution)
        self.portfolio = PortfolioState(
            capital=config.starting_capital,
            peak_capital=config.starting_capital,
        )
        self.signals_generated: List[Signal] = []
        self._all_signals: List[Signal] = []  # including non-actionable

    def _compute_signal(self, market) -> Optional[Signal]:
        """
        Generate a signal for a single market.
        """
        mid = market.market_id
        model_prob = self.prob_engine.get_combined_probability(mid)
        market_price = market.yes_price

        # Edge calculation
        edge = model_prob - market_price

        # Direction
        if edge > 0:
            direction = "BUY_YES"
        elif edge < 0:
            direction = "BUY_NO"
            edge = -edge  # Make positive for sizing
            model_prob = 1.0 - model_prob  # Flip for BUY_NO
            market_price = 1.0 - market_price
        else:
            return None

        # Standard error of the edge (approximate)
        se_approx = max(0.01, np.sqrt(market_price * (1 - market_price) / 10000))
        edge_zscore = edge / se_approx

        # Confidence classification
        if edge_zscore > 3.0 and edge > self.config.risk.min_edge_threshold * 2:
            confidence = "high"
        elif edge_zscore > 2.0 and edge > self.config.risk.min_edge_threshold:
            confidence = "medium"
        else:
            confidence = "low"

        # Kelly sizing
        suggested_size = self.risk_manager.kelly_size(
            edge=edge,
            market_price=market_price,
            capital=self.portfolio.capital,
        )

        # Components from probability engine
        components = self.prob_engine.estimates.get(mid, {})

        # Create signal object
        sig_direction = "BUY_YES" if (model_prob - market_price) == edge else "BUY_NO"
        # Restore original values for display
        orig_estimates = self.prob_engine.estimates.get(mid, {})
        orig_model_prob = self.prob_engine.get_combined_probability(mid)
        orig_edge = orig_model_prob - market.yes_price

        signal = Signal(
            market_id=mid,
            question=market.question,
            direction="BUY_YES" if orig_edge >= 0 else "BUY_NO",
            market_price=market.yes_price,
            model_probability=orig_model_prob,
            edge=orig_edge,
            edge_zscore=edge_zscore if orig_edge >= 0 else -edge_zscore,
            confidence=confidence,
            suggested_size=suggested_size,
            timestamp=datetime.utcnow().isoformat(),
            components=components,
        )

        return signal

    def process_market_batch(self, markets: list) -> List[Signal]:
        """
        Generate signals for a batch of markets.
        Returns only actionable signals (above edge threshold), sorted by |edge|.
        """
        actionable = []

        for market in markets:
            try:
                signal = self._compute_signal(market)
                if signal is None:
                    continue

                self._all_signals.append(signal)

                # Filter: must exceed minimum edge
                if abs(signal.edge) >= self.config.risk.min_edge_threshold:
                    actionable.append(signal)
                    self.signals_generated.append(signal)
            except Exception as e:
                logger.warning(f"Signal generation failed for {market.market_id}: {e}")

        # Sort by absolute edge descending
        actionable.sort(key=lambda s: abs(s.edge), reverse=True)
        return actionable

    def execute_signal(self, signal: Signal, market) -> Dict:
        """
        Execute a signal through risk checks and simulated execution.
        """
        # Risk check
        allowed, reasons = self.risk_manager.check_portfolio_limits(
            self.portfolio, signal.suggested_size
        )

        if not allowed:
            return {
                "signal": signal,
                "executed": False,
                "size": signal.suggested_size,
                "fill_price": 0.0,
                "slippage": 0.0,
                "fees": 0.0,
                "reasons": reasons,
            }

        return self.execution_engine.execute(signal, market, self.portfolio)

    def get_performance_report(self) -> Dict:
        """
        Generate comprehensive performance report.
        """
        # Portfolio summary
        portfolio_report = {
            "capital": self.portfolio.capital,
            "deployed": self.portfolio.deployed_capital(),
            "utilization": self.portfolio.utilization(),
            "n_positions": len(self.portfolio.positions),
            "n_trades": len(self.portfolio.trade_history),
            "total_pnl": self.portfolio.total_pnl,
            "max_drawdown": self.portfolio.max_drawdown,
        }

        # Signal summary
        all_edges = [abs(s.edge) for s in self._all_signals]
        actionable_signals = [s for s in self._all_signals
                              if abs(s.edge) >= self.config.risk.min_edge_threshold]

        signal_report = {
            "total_generated": len(self._all_signals),
            "actionable": len(actionable_signals),
            "hit_rate": len(actionable_signals) / max(len(self._all_signals), 1),
            "high_confidence": len([s for s in actionable_signals if s.confidence == "high"]),
            "medium_confidence": len([s for s in actionable_signals if s.confidence == "medium"]),
            "low_confidence": len([s for s in actionable_signals if s.confidence == "low"]),
            "avg_absolute_edge": float(np.mean(all_edges)) if all_edges else 0.0,
        }

        # Execution summary
        executed_trades = [e for e in self.execution_engine.executions if e["executed"]]
        exec_report = {
            "total_executions": len(executed_trades),
            "avg_slippage": float(np.mean([e["slippage"] for e in executed_trades])) if executed_trades else 0.0,
            "avg_fees": float(np.mean([e["fees"] for e in executed_trades])) if executed_trades else 0.0,
            "total_fees": sum(e["fees"] for e in executed_trades),
            "profitable_pct": 0.0,  # Would need resolution data
        }

        return {
            "portfolio": portfolio_report,
            "signals": signal_report,
            "execution": exec_report,
            "timestamp": datetime.utcnow().isoformat(),
        }
